import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// Components
import Head from "./head";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from "@/components/ui/toaster";
import Header from "@/components/Header";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <Head />
      <body className="w-full min-h-screen font-roboto scroll-smooth">
        <Header />
        <main className="w-full flex flex-col items-center justify-start mx-auto mt-[3.8rem]">
          {children}
        </main>
      </body>
      <Toaster />
    </html>
  );
}
